apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  server.secretkey: Kc8Rzaa9KOK0hs8wycDI/nPcLxdSWyrPY4vZ6Xx79uo=
  webhook.github.secret: GNJxYPu/QRQa0N1ZRXbWS5XjTEiMk9g5BfgLYzNFCrY=
