apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Capzula-INC/argocd.git'
    targetRevision: HEAD
    path: redis-dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
